# Generated by Django 5.1.5 on 2025-02-16 20:29

import apps.celery_screening.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_filter', models.CharField(default='default_filter', max_length=200)),
                ('symbols', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticker24hrUSDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('open_time', models.BigIntegerField(db_index=True, default=0)),
                ('open_price', apps.celery_screening.models.CustomDecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('high_price', apps.celery_screening.models.CustomDecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('low_price', apps.celery_screening.models.CustomDecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('volume', apps.celery_screening.models.CustomDecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('close_time', models.BigIntegerField(db_index=True, default=0)),
                ('count', models.BigIntegerField()),
                ('price_change', apps.celery_screening.models.CustomDecimalField(decimal_places=10, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_change_percent', models.DecimalField(decimal_places=5, max_digits=30)),
                ('weighted_avg_price', apps.celery_screening.models.CustomDecimalField(decimal_places=10, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('prev_close_price', apps.celery_screening.models.CustomDecimalField(decimal_places=10, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_price', apps.celery_screening.models.CustomDecimalField(decimal_places=10, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_qty', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('bid_price', apps.celery_screening.models.CustomDecimalField(decimal_places=10, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('bid_qty', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ask_price', apps.celery_screening.models.CustomDecimalField(decimal_places=10, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('ask_qty', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('quote_volume', models.DecimalField(decimal_places=15, max_digits=35, validators=[django.core.validators.MinValueValidator(0)])),
                ('first_id', models.BigIntegerField()),
                ('last_id', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Candles1mUSDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('open_time', models.BigIntegerField(db_index=True, default=0)),
                ('open_price', apps.celery_screening.models.CustomDecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('high_price', apps.celery_screening.models.CustomDecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('low_price', apps.celery_screening.models.CustomDecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('volume', apps.celery_screening.models.CustomDecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('close_time', models.BigIntegerField(db_index=True, default=0)),
                ('count', models.BigIntegerField()),
                ('close_price', apps.celery_screening.models.CustomDecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('base_asset_volume', apps.celery_screening.models.CustomDecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('taker_buy_volume', apps.celery_screening.models.CustomDecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('taker_buy_base_asset_volume', apps.celery_screening.models.CustomDecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'open_time'], name='celery_scre_symbol_c7ccb6_idx')],
            },
        ),
        migrations.CreateModel(
            name='AllCandlesUSDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_candles_1m_in_1hr', models.JSONField(default=list)),
                ('all_candles_1hr_in_24hr', models.JSONField(default=list)),
                ('all_candles_1d_in_1mo', models.JSONField(default=list)),
                ('all_candles_1mo_in_1y', models.JSONField(default=list)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celery_screening.candles1musdt', to_field='symbol')),
            ],
        ),
    ]
