# Generated by Django 5.1.5 on 2025-02-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_screening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcandlesusdt',
            name='symbol',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
