# Generated by Django 5.1.5 on 2025-02-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celery_screening', '0002_alter_allcandlesusdt_symbol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcandlesusdt',
            old_name='all_candles_1m_in_1hr',
            new_name='all_candles_5m_in_24hr',
        ),
    ]
